/// WireGuard adapter — implements VpnPort using wg/wg-quick CLI tools (Tarea 162)
///
/// Uses std::process::Command (not tokio::process) to keep the trait synchronous.
/// All wg/wg-quick calls require root privileges (already guaranteed by CLI).
use crate::domain::vpn::{VpnError, VpnServer};
use crate::ports::vpn::{VpnInterfaceStatus, VpnPeerStatus, VpnPort};

const WG_CONF_DIR: &str = "/etc/wireguard";

pub struct WireGuardAdapter;

impl Default for WireGuardAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl WireGuardAdapter {
    pub fn new() -> Self {
        Self
    }

    fn run_cmd(args: &[&str]) -> Result<String, VpnError> {
        let output = std::process::Command::new(args[0])
            .args(&args[1..])
            .output()
            .map_err(|e| VpnError::SystemError(format!("Failed to run {:?}: {}", args[0], e)))?;
        if output.status.success() {
            Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
            Err(VpnError::SystemError(format!("{}: {}", args[0], stderr)))
        }
    }

    fn conf_path(interface: &str) -> String {
        format!("{}/{}.conf", WG_CONF_DIR, interface)
    }
}

impl VpnPort for WireGuardAdapter {
    fn is_installed(&self) -> bool {
        std::process::Command::new("wg")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    fn generate_private_key(&self) -> Result<String, VpnError> {
        Self::run_cmd(&["wg", "genkey"])
    }

    fn derive_public_key(&self, private_key: &str) -> Result<String, VpnError> {
        use std::io::Write;
        let mut child = std::process::Command::new("wg")
            .arg("pubkey")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
            .map_err(|e| VpnError::SystemError(format!("wg pubkey spawn: {}", e)))?;
        if let Some(stdin) = child.stdin.as_mut() {
            stdin
                .write_all(private_key.as_bytes())
                .map_err(|e| VpnError::SystemError(format!("wg pubkey stdin: {}", e)))?;
        }
        let out = child
            .wait_with_output()
            .map_err(|e| VpnError::SystemError(format!("wg pubkey wait: {}", e)))?;
        if out.status.success() {
            Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
        } else {
            Err(VpnError::SystemError(
                String::from_utf8_lossy(&out.stderr).trim().to_string(),
            ))
        }
    }

    fn generate_preshared_key(&self) -> Result<String, VpnError> {
        Self::run_cmd(&["wg", "genpsk"])
    }

    fn create_server_config(&self, server: &VpnServer, private_key: &str) -> Result<(), VpnError> {
        std::fs::create_dir_all(WG_CONF_DIR)
            .map_err(|e| VpnError::SystemError(format!("Cannot create {}: {}", WG_CONF_DIR, e)))?;

        let mut config = format!(
            "# Enola WireGuard VPN — {}\n\
             # Generated by enola-cli. Do not edit manually.\n\n\
             [Interface]\n\
             PrivateKey = {}\n\
             Address = {}/32\n\
             ListenPort = {}\n\
             SaveConfig = false\n\
             # PostUp/PostDown for NAT (enable if internet forwarding needed)\n\
             # PostUp = iptables -A FORWARD -i {} -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE\n\
             # PostDown = iptables -D FORWARD -i {} -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE\n",
            server.interface,
            private_key,
            server.server_ip,
            server.port,
            server.interface,
            server.interface,
        );

        for peer in &server.peers {
            config.push_str(&format!(
                "\n# Peer: {}\n[Peer]\nPublicKey = {}\nAllowedIPs = {}/32\n",
                peer.name, peer.public_key, peer.ip_address,
            ));
            if let Some(psk) = &peer.preshared_key {
                config.push_str(&format!("PresharedKey = {}\n", psk));
            }
        }

        let path = Self::conf_path(&server.interface);
        crate::infrastructure::atomic_secret_file::write_secret_atomically(
            std::path::Path::new(&path),
            config.as_bytes(),
        )
        .map_err(|e| VpnError::SystemError(format!("Cannot write {}: {}", path, e)))?;

        Ok(())
    }

    fn start_interface(&self, interface: &str) -> Result<(), VpnError> {
        Self::run_cmd(&["wg-quick", "up", interface])?;
        Ok(())
    }

    fn stop_interface(&self, interface: &str) -> Result<(), VpnError> {
        Self::run_cmd(&["wg-quick", "down", interface])?;
        Ok(())
    }

    fn get_interface_status(&self, interface: &str) -> Result<VpnInterfaceStatus, VpnError> {
        let output = Self::run_cmd(&["wg", "show", interface])?;
        parse_wg_show_output(interface, &output)
    }

    fn list_interfaces(&self) -> Result<Vec<String>, VpnError> {
        let output = Self::run_cmd(&["wg", "show", "interfaces"]).unwrap_or_default();
        let interfaces: Vec<String> = output
            .split_whitespace()
            .filter(|s| !s.is_empty())
            .map(|s| s.to_string())
            .collect();
        Ok(interfaces)
    }

    fn add_peer(
        &self,
        interface: &str,
        public_key: &str,
        allowed_ip: &str,
        preshared_key: Option<&str>,
    ) -> Result<(), VpnError> {
        let ip_with_mask = if allowed_ip.contains('/') {
            allowed_ip.to_string()
        } else {
            format!("{}/32", allowed_ip)
        };

        let mut args = vec![
            "wg",
            "set",
            interface,
            "peer",
            public_key,
            "allowed-ips",
            &ip_with_mask,
        ];

        // We need to handle preshared key differently since we need the string to live long enough
        let psk_arg;
        if let Some(psk) = preshared_key {
            psk_arg = format!("preshared-key /dev/stdin <<< {}", psk);
            // Use tempfile with 0600 permissions and random name (anti-TOCTOU)
            let mut tmp = tempfile::NamedTempFile::new()
                .map_err(|e| VpnError::SystemError(format!("psk tmp file: {}", e)))?;
            std::io::Write::write_all(&mut tmp, psk.as_bytes())
                .map_err(|e| VpnError::SystemError(format!("psk write: {}", e)))?;
            let tmp_path = tmp.path().to_path_buf();
            args.push("preshared-key");
            args.push(tmp_path.to_str().unwrap());
            let result = Self::run_cmd(&args);
            drop(tmp);
            result?;
            let _ = psk_arg; // suppress unused warning
        } else {
            Self::run_cmd(&args)?;
        }
        Ok(())
    }

    fn remove_peer(&self, interface: &str, public_key: &str) -> Result<(), VpnError> {
        Self::run_cmd(&["wg", "set", interface, "peer", public_key, "remove"])?;
        Ok(())
    }

    fn generate_peer_config(
        &self,
        peer_name: &str,
        peer_private_key: &str,
        peer_ip: &str,
        server_public_key: &str,
        server_endpoint: &str,
        server_port: u16,
        dns: Option<&str>,
        preshared_key: Option<&str>,
    ) -> String {
        let dns_line = dns.map(|d| format!("DNS = {}\n", d)).unwrap_or_default();
        let psk_line = preshared_key
            .map(|k| format!("PresharedKey = {}\n", k))
            .unwrap_or_default();

        format!(
            "# WireGuard Client Config — {}\n\
             # Generated by enola-cli\n\n\
             [Interface]\n\
             PrivateKey = {}\n\
             Address = {}/32\n\
             {}\n\
             [Peer]\n\
             PublicKey = {}\n\
             {}Endpoint = {}:{}\n\
             AllowedIPs = 0.0.0.0/0, ::/0\n\
             PersistentKeepalive = 25\n",
            peer_name,
            peer_private_key,
            peer_ip,
            dns_line,
            server_public_key,
            psk_line,
            server_endpoint,
            server_port,
        )
    }

    fn enable_autostart(&self, interface: &str) -> Result<(), VpnError> {
        Self::run_cmd(&["systemctl", "enable", &format!("wg-quick@{}", interface)])?;
        Ok(())
    }

    fn disable_autostart(&self, interface: &str) -> Result<(), VpnError> {
        Self::run_cmd(&["systemctl", "disable", &format!("wg-quick@{}", interface)])?;
        Ok(())
    }

    fn delete_config(&self, interface: &str) -> Result<(), VpnError> {
        let path = Self::conf_path(interface);
        if std::path::Path::new(&path).exists() {
            std::fs::remove_file(&path)
                .map_err(|e| VpnError::SystemError(format!("Cannot delete {}: {}", path, e)))?;
        }
        Ok(())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Parse `wg show {interface}` output
// ─────────────────────────────────────────────────────────────────────────────

fn parse_wg_show_output(interface: &str, output: &str) -> Result<VpnInterfaceStatus, VpnError> {
    let mut public_key = String::new();
    let mut listen_port = 0u16;
    let mut peers: Vec<VpnPeerStatus> = Vec::new();
    let mut current_peer: Option<VpnPeerStatus> = None;

    for line in output.lines() {
        let trimmed = line.trim();
        if let Some(val) = trimmed.strip_prefix("public key: ") {
            public_key = val.to_string();
        } else if let Some(val) = trimmed.strip_prefix("listening port: ") {
            listen_port = val.parse().unwrap_or(0);
        } else if let Some(val) = trimmed.strip_prefix("peer: ") {
            if let Some(p) = current_peer.take() {
                peers.push(p);
            }
            current_peer = Some(VpnPeerStatus {
                public_key: val.to_string(),
                allowed_ips: Vec::new(),
                endpoint: None,
                latest_handshake: None,
                transfer_rx_bytes: 0,
                transfer_tx_bytes: 0,
            });
        } else if let Some(p) = current_peer.as_mut() {
            if let Some(val) = trimmed.strip_prefix("endpoint: ") {
                p.endpoint = Some(val.to_string());
            } else if let Some(val) = trimmed.strip_prefix("allowed ips: ") {
                p.allowed_ips = val.split(',').map(|s| s.trim().to_string()).collect();
            } else if let Some(val) = trimmed.strip_prefix("latest handshake: ") {
                p.latest_handshake = Some(val.to_string());
            } else if let Some(val) = trimmed.strip_prefix("transfer: ") {
                // "transfer: 1.23 KiB received, 4.56 KiB sent"
                let parts: Vec<&str> = val.split(',').collect();
                if parts.len() >= 2 {
                    p.transfer_rx_bytes = parse_transfer_bytes(parts[0].trim());
                    p.transfer_tx_bytes = parse_transfer_bytes(parts[1].trim());
                }
            }
        }
    }
    if let Some(p) = current_peer.take() {
        peers.push(p);
    }

    Ok(VpnInterfaceStatus {
        interface: interface.to_string(),
        public_key,
        listen_port,
        peers,
    })
}

fn parse_transfer_bytes(s: &str) -> u64 {
    // "1.23 KiB received" / "4.56 MiB sent"
    let parts: Vec<&str> = s.split_whitespace().collect();
    if parts.len() < 2 {
        return 0;
    }
    let num: f64 = parts[0].parse().unwrap_or(0.0);
    let multiplier = match parts[1].to_lowercase().as_str() {
        "b" => 1.0,
        "kib" => 1024.0,
        "mib" => 1024.0 * 1024.0,
        "gib" => 1024.0 * 1024.0 * 1024.0,
        _ => 1.0,
    };
    (num * multiplier) as u64
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_wg_show_no_peers() {
        let output = "  interface: wg0\n  public key: xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=\n  listening port: 51820\n";
        let status = parse_wg_show_output("wg0", output).unwrap();
        assert_eq!(status.interface, "wg0");
        assert_eq!(status.listen_port, 51820);
        assert!(status.peers.is_empty());
    }

    #[test]
    fn test_parse_wg_show_with_peer() {
        let output = "\
  interface: wg0
  public key: xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
  listening port: 51820

  peer: PEER_PUB_KEY_HERE_BASE64_44CHARS_PADDING=
    endpoint: 1.2.3.4:51820
    allowed ips: 10.8.0.2/32
    latest handshake: 2 minutes, 5 seconds ago
    transfer: 1.23 KiB received, 456 B sent
";
        let status = parse_wg_show_output("wg0", output).unwrap();
        assert_eq!(status.listen_port, 51820);
        assert_eq!(status.peers.len(), 1);
        let p = &status.peers[0];
        assert_eq!(p.endpoint, Some("1.2.3.4:51820".to_string()));
        assert_eq!(p.allowed_ips, vec!["10.8.0.2/32"]);
        assert!(p.transfer_rx_bytes > 0);
    }

    #[test]
    fn test_parse_transfer_bytes_kib() {
        assert_eq!(parse_transfer_bytes("1.00 KiB received"), 1024);
    }

    #[test]
    fn test_parse_transfer_bytes_mib() {
        assert_eq!(parse_transfer_bytes("1.00 MiB sent"), 1024 * 1024);
    }

    #[test]
    fn test_parse_transfer_bytes_b() {
        assert_eq!(parse_transfer_bytes("456 B sent"), 456);
    }

    #[test]
    fn test_generate_peer_config_format() {
        let adapter = WireGuardAdapter::new();
        let config = adapter.generate_peer_config(
            "laptop",
            "PRIVATE_KEY",
            "10.8.0.2",
            "SERVER_PUB_KEY",
            "vpn.example.com",
            51820,
            Some("1.1.1.1"),
            None,
        );
        assert!(config.contains("[Interface]"));
        assert!(config.contains("[Peer]"));
        assert!(config.contains("10.8.0.2/32"));
        assert!(config.contains("vpn.example.com:51820"));
        assert!(config.contains("DNS = 1.1.1.1"));
        assert!(config.contains("PersistentKeepalive = 25"));
    }

    #[test]
    fn test_generate_peer_config_with_psk() {
        let adapter = WireGuardAdapter::new();
        let config = adapter.generate_peer_config(
            "phone",
            "PRIV",
            "10.8.0.3",
            "PUB",
            "1.2.3.4",
            51820,
            None,
            Some("PRESHARED_KEY"),
        );
        assert!(config.contains("PresharedKey = PRESHARED_KEY"));
    }
}
