/// Socat bridge adapter — implements VpnBridgePort using a systemd unit (VPN over Tor)
///
/// Tunnels WireGuard's UDP traffic over TCP so it can be exposed through a
/// Tor hidden service. Uses `socat` managed by a systemd unit so the bridge
/// survives reboots. All calls require root privileges (already guaranteed by CLI).
use crate::domain::vpn::VpnError;
use crate::ports::vpn_bridge::VpnBridgePort;

const SYSTEMD_UNIT_DIR: &str = "/etc/systemd/system";

pub struct SocatBridgeAdapter;

impl Default for SocatBridgeAdapter {
    fn default() -> Self {
        Self::new()
    }
}

impl SocatBridgeAdapter {
    pub fn new() -> Self {
        Self
    }

    fn run_cmd(args: &[&str]) -> Result<String, VpnError> {
        let output = std::process::Command::new(args[0])
            .args(&args[1..])
            .output()
            .map_err(|e| VpnError::SystemError(format!("Failed to run {:?}: {}", args[0], e)))?;
        if output.status.success() {
            Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
            Err(VpnError::SystemError(format!("{}: {}", args[0], stderr)))
        }
    }

    fn unit_name(interface: &str) -> String {
        format!("enola-vpn-bridge-{}.service", interface)
    }

    fn unit_path(interface: &str) -> String {
        format!("{}/{}", SYSTEMD_UNIT_DIR, Self::unit_name(interface))
    }

    /// Generate the systemd unit file content (pure function, testable).
    fn unit_content(interface: &str, tcp_port: u16, udp_port: u16) -> String {
        format!(
            "# Enola VPN UDP-TCP bridge — {} (WireGuard over Tor)\n\
             # Generated by enola-cli. Do not edit manually.\n\n\
             [Unit]\n\
             Description=Enola VPN UDP-TCP bridge for {} (WireGuard over Tor)\n\
             After=network.target\n\n\
             [Service]\n\
             Type=simple\n\
             ExecStart=/usr/bin/socat TCP-LISTEN:{},fork,reuseaddr UDP:127.0.0.1:{}\n\
             Restart=on-failure\n\
             RestartSec=5\n\n\
             [Install]\n\
             WantedBy=multi-user.target\n",
            interface, interface, tcp_port, udp_port,
        )
    }
}

impl VpnBridgePort for SocatBridgeAdapter {
    fn start_bridge(&self, interface: &str, tcp_port: u16, udp_port: u16) -> Result<(), VpnError> {
        let path = Self::unit_path(interface);
        std::fs::write(&path, Self::unit_content(interface, tcp_port, udp_port))
            .map_err(|e| VpnError::SystemError(format!("Cannot write {}: {}", path, e)))?;

        Self::run_cmd(&["systemctl", "daemon-reload"])?;
        Self::run_cmd(&["systemctl", "enable", "--now", &Self::unit_name(interface)])?;
        Ok(())
    }

    fn stop_bridge(&self, interface: &str) -> Result<(), VpnError> {
        // Disable/stop first (ignore error if already stopped).
        let _ = Self::run_cmd(&["systemctl", "disable", "--now", &Self::unit_name(interface)]);

        let path = Self::unit_path(interface);
        if std::path::Path::new(&path).exists() {
            std::fs::remove_file(&path)
                .map_err(|e| VpnError::SystemError(format!("Cannot delete {}: {}", path, e)))?;
        }
        let _ = Self::run_cmd(&["systemctl", "daemon-reload"]);
        Ok(())
    }

    fn is_bridge_active(&self, interface: &str) -> bool {
        Self::run_cmd(&["systemctl", "is-active", &Self::unit_name(interface)])
            .map(|out| out == "active")
            .unwrap_or(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_unit_content_contains_ports() {
        let content = SocatBridgeAdapter::unit_content("wg0", 51821, 51820);
        assert!(content.contains("TCP-LISTEN:51821"));
        assert!(content.contains("UDP:127.0.0.1:51820"));
        assert!(content.contains("Description=Enola VPN UDP-TCP bridge for wg0"));
        assert!(content.contains("Restart=on-failure"));
    }

    #[test]
    fn test_unit_name_format() {
        assert_eq!(
            SocatBridgeAdapter::unit_name("wg0"),
            "enola-vpn-bridge-wg0.service"
        );
    }
}
